name: CI with SonarQube

on:
  push:
    branches: [ development ]

jobs:
  #############################
  # SONARQUBE ONLY
  #############################
  sonar:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      
      - name: Check for pre-generated coverage reports
        run: |
          # Check if required files exist
          if [ ! -f "coverage/frontend/lcov.info" ]; then
            echo "Error: coverage/frontend/lcov.info not found! Please generate frontend coverage locally first."
            exit 1
          fi
          
          if [ ! -f "coverage/backend/coverage.xml" ]; then
            echo "Error: coverage/backend/coverage.xml not found! Please generate backend coverage locally first."
            exit 1
          fi
          
          if [ ! -f "tests/reports/merged-test-report.xml" ]; then
            echo "Error: tests/reports/merged-test-report.xml not found! Please generate and merge test reports locally first."
            exit 1
          fi
          
          echo "✓ All required coverage files found"
  
      - name: Run SonarQube Scanner
        uses: sonarsource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.sources=. 
            -Dsonar.tests=tests
            -Dsonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info
            -Dsonar.python.coverage.reportPaths=coverage/backend/coverage.xml
            -Dsonar.testExecutionReportPaths=tests/reports/merged-test-report.xml